### ISSUE TITLE
Automating the installation step

### ISSUE THREAD

**Issue by hayesall** [xinyiguan/py2lispIDyOM#12]
The installation is pretty tricky at the moment, following from the [`idyom` installation instructions](https://github.com/mtpearce/idyom/wiki/Installation).

**Recommmendation**: Figure out how to automate installation on a common platform (e.g. Ubuntu).

## `sbcl`

This one should be pretty straightforward:

```bash
curl -L http://prdownloads.sourceforge.net/sbcl/sbcl-2.2.9-x86-64-linux-binary.tar.bz2 > sbcl-2.2.9-x86-64-linux-binary.tar.bz2
bzip2 -cd sbcl-2.2.9-x86-64-linux-binary.tar.bz2 | tar xvf -
cd sbcl-2.2.9-x86-linux
sudo sh install.sh
```

## `quicklisp`

This one might be trickier. The [`quicklisp` installation instructions](https://www.quicklisp.org/beta/) currently suggest installing in interactive mode.

I didn't test it yet (I'm less familiar with `sbcl`), but using `--eval` might be one path to follow here:

```bash
sbcl --eval '(quicklisp-quickstart:install)'
```

## `sqlite3`

This one should be easy.

```bash
sudo apt install sqlite3
```

## `IDyOM`

This one feels fairly straightforward after figuring out the username (`whoami`), and evaluating a few expressions to make sure packages are correctly downloaded.

Here is a rough draft for the fourth step:

```bash
echo '(ql:quickload "clsql")' >> .sbclrc
echo '(defun start-idyom ()' >> .sbclrc
echo "  (defvar *idyom-root* \"/home/$(whoami)/idyom/\")" >> .sbclrc
echo "  (ql:quickload \"idyom\")" >> .sbclrc
echo "  (clsql:connect '(\"/home/$(whoami)/idyom/db/database.sqlite\") :if-exists :old :database-type :sqlite3))" >> .sbclrc
```

**Comment by xinyiguan** [comment]
Thank you so much for outlining the steps. I've written up a shell script to automate the IDyOM installation process (for MacOS). The instructions are also updated in the README.

**Comment by hayesall** [comment]
Nice! I do not have a mac to text on, but the setup looks good.

**Comment by hayesall** [comment]
Following up on #10: now that there's a way to automatically install dependencies, this should be incorporated into the continuous integration settings.

Right now, these lines are missed in the coverage step:

https://github.com/xinyiguan/py2lispIDyOM/blob/5d04e44be3df7a04d41cabf3a8da772a4f85a4d4/py2lispIDyOM/run.py#L113-L125

I'll be more confident about testing when everything is in CI.

**Comment by xinyiguan** [comment]
I just incorporated the installation to CI and added additional test to cover the `.run()` method. I changed to only the macos platform in the `tests.yml` workflow for the test because the install shell script works for (and is only tested on) macos for the moment.
